version: '3.7'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  frontend:
    restart: "no"
  database:
    restart: "no"
  migrations:
    restart: "no"
  resources:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  uuid-generation:
    restart: "no"
  mandatendatabank-consumer:
    environment:
      DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
    restart: "no"
  besluiten-consumer:
    environment:
      DCR_DISABLE_INITIAL_SYNC: "false" # uncomment to enable initial sync
    restart: "no"
