version: '3.7'

services:
  besluiten-consumer:
    image: lblod/delta-consumer:0.0.12
    environment:
      DCR_SYNC_BASE_URL: "https://dev.harvesting-self-service.lblod.info/"
      DCR_SERVICE_NAME: "besluiten-consumer"
      DCR_SYNC_FILES_PATH: "/sync/besluiten/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/besluiten"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/besluitenSyncing"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/besluiten-consumer"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_FILE_FOLDER: "/consumer-files"
      DCR_DISABLE_INITIAL_SYNC: "true" # toggle this in override, leave 'true' in default docker-compose.yml
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: 'true'
      BATCH_SIZE: 1000
    volumes:
      - ./data/files/consumer-files/besluiten:/consumer-files/
      - ./config/consumer/example-custom-dispatching:/config/triples-dispatching/custom-dispatching
    labels:
      - "logging=true"

  database:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config

  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
      
  resources:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
